sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:

  # Cabal
  - ghc: 8.6.5

install:
  - |
      ghc --version
      cabal --version
      cabal update
      cabal build --disable-optimization 


notifications:
  email: false